In [1]:
import pandas as pd
import numpy as np

In [2]:
proyecto=pd.read_csv('https://raw.githubusercontent.com/Robertozimri/Robertozimri/main/db_proyecto.csv', sep=';')
proyecto.head()

,Tipo,Valor,Barrio,Alcaldia,Area,Recamaras,Baños,Estacionamientos,ValorMantenimiento,Caracteristicas
0,Departamento,681.50,Barrio del Niño Jesús,Tlalpan,85,3,2,1.0,40.7,"[Planta baja, Buena iluminación, Cocina integr..."
1,Departamento,681.55,Carola,Alvaro Obregón,60,2,2,2.0,0.0,"[Buena iluminación,Sala Comedor,Cocina Equipad..."
2,Departamento,864.80,Condesa,Cuauhtémoc,70,2,2,1.0,84.6,"[Vigilancia 24 horas, Gimnasio, Roof Garden co..."
3,Casa,1363.00,Contadero,Cuajimalpa de Morelos,131,3,2,2.0,0.0,"[Sala, Comedor, Cocina integral,Área de lavado..."
4,Departamento,705.00,Del Valle,Benito Juárez,79,2,2,1.0,61.1,"[Recámara con vestidor y baño, Closet,Comedor ..."

In [ ]:
proyecto['ValorTotal'] = proyecto['Valor'] + proyecto['ValorMantenimiento']
proyecto.head()

,Tipo,Valor,Barrio,Alcaldia,Area,Recamaras,Baños,Estacionamientos,ValorMantenimiento,Caracteristicas,ValorTotal
0,Departamento,681.50,Barrio del Niño Jesús,Tlalpan,85,3,2,1.0,40.7,"[Planta baja, Buena iluminación, Cocina integr...",722.20
1,Departamento,681.55,Carola,Alvaro Obregón,60,2,2,2.0,0.0,"[Buena iluminación,Sala Comedor,Cocina Equipad...",681.55
2,Departamento,864.80,Condesa,Cuauhtémoc,70,2,2,1.0,84.6,"[Vigilancia 24 horas, Gimnasio, Roof Garden co...",949.40
3,Casa,1363.00,Contadero,Cuajimalpa de Morelos,131,3,2,2.0,0.0,"[Sala, Comedor, Cocina integral,Área de lavado...",1363.00
4,Departamento,705.00,Del Valle,Benito Juárez,79,2,2,1.0,61.1,"[Recámara con vestidor y baño, Closet,Comedor ...",766.10

In [ ]:
proyecto.groupby(by=['Tipo']) [['ValorTotal','Area']].mean().round(2)

              ValorTotal    Area
Tipo
Casa              944.80  168.56
Departamento      939.06  100.64

In [ ]:
valor_medio_barrio=proyecto.groupby(by=['Barrio']) [['ValorTotal','Area']].mean().round(2)
valor_medio_barrio

                            ValorTotal   Area
Barrio
Ampliación Paraje San Juan         NaN  129.0
Anzures                            NaN  349.0
Barrio del Niño Jesús           722.20   85.0
Carola                          681.55   60.0
Condesa                         949.40   70.0
Contadero                      1363.00  131.0
Cuajimalpa                         NaN   40.0
Del Valle                       828.77   90.0
Ex Hacienda Coapa              1175.00  153.0
Floresta Coyoacán               751.00  180.0
Héroes de Padierna              459.60   90.0
Locaxco                         727.50   62.0
Lomas de Santa Fe              1339.50  150.0
Moctezuma                          NaN   30.0
Narciso Mendoza                 704.00  120.0
Pedregal de Coyoacán           1081.00  157.0
Plutarco Elías Calles           469.00  130.0
Polanco                        2114.00  385.0
Popotla                         470.00   70.0
Reforma Social                     NaN  117.0
Roma Sur                        752.00   85.0
San Pedro de los Pinos          845.00   84.0
Santa Fe Cuajimalpa             952.20   77.8
Vertiz Narvarte                1315.50  197.5

In [ ]:
barrios=['Carola', 'Del Valle', 'Condesa', 'Moctezuma', 'Santa Fe Cuajimalpa']
valor_medio_barrio.loc[barrios]

                     ValorTotal  Area
Barrio
Carola                   681.55  60.0
Del Valle                828.77  90.0
Condesa                  949.40  70.0
Moctezuma                   NaN  30.0
Santa Fe Cuajimalpa      952.20  77.8

In [ ]:
proyecto['Tipo'].value_counts(sort=False)#.rename_axis('Tipo de Vivienda').to_frame('Porcentual (x)')*100

Departamento    22
Casa             9
Name: Tipo, dtype: int64

In [ ]:
proyecto['Recamaras'].value_counts(normalize=True, sort=False).rename_axis('Numero de recamaras').to_frame('Porcentual (x)')*100

                     Porcentual (x)
Numero de recamaras
3                         35.483871
2                         29.032258
1                         22.580645
4                          9.677419
5                          3.225806

In [ ]:
proyecto['Baños'].value_counts(normalize=True, sort=False).rename_axis('Numero de baños').to_frame('Porcentual (x)')*100

                 Porcentual (x)
Numero de baños
2                     38.709677
1                     41.935484
4                      3.225806
3                     12.903226
5                      3.225806

In [ ]:
proyecto['Estacionamientos'].value_counts(normalize=True, sort=False).rename_axis('Numero de Estacionamientos').to_frame('Porcentual (x)')*100

                            Porcentual (x)
Numero de Estacionamientos
1.0                              41.379310
2.0                              41.379310
3.0                              13.793103
4.0                               3.448276

In [ ]:
metor_cuadrado=proyecto.groupby(by=['Tipo','Recamaras']) [['Area']].mean()
metor_cuadrado

                              Area
Tipo         Recamaras
Casa         3          174.000000
             4          137.333333
             5          235.000000
Departamento 1           56.142857
             2           88.777778
             3          170.333333