In [1]:
import pandas as pd

In [2]:
proyecto=pd.read_csv('https://raw.githubusercontent.com/Robertozimri/Robertozimri/main/db_proyecto.csv', sep=';')
proyecto.head()

,Tipo,Valor,Barrio,Alcaldia,Area,Recamaras,Baños,Estacionamientos,ValorMantenimiento,Caracteristicas
0,Departamento,681.50,Barrio del Niño Jesús,Tlalpan,85,3,2,1.0,40.7,"[Planta baja, Buena iluminación, Cocina integr..."
1,Departamento,681.55,Carola,Alvaro Obregón,60,2,2,2.0,0.0,"[Buena iluminación,Sala Comedor,Cocina Equipad..."
2,Departamento,864.80,Condesa,Cuauhtémoc,70,2,2,1.0,84.6,"[Vigilancia 24 horas, Gimnasio, Roof Garden co..."
3,Casa,1363.00,Contadero,Cuajimalpa de Morelos,131,3,2,2.0,0.0,"[Sala, Comedor, Cocina integral,Área de lavado..."
4,Departamento,705.00,Del Valle,Benito Juárez,79,2,2,1.0,61.1,"[Recámara con vestidor y baño, Closet,Comedor ..."

In [3]:
proyecto.describe()

,Valor,Area,Recamaras,Baños,Estacionamientos,ValorMantenimiento
count,30.000000,31.000000,31.000000,31.000000,29.000000,25.000000
mean,881.721667,120.354839,2.419355,1.870968,1.793103,30.744000
std,403.018840,80.518134,1.057487,0.991361,0.818505,45.857461
min,211.500000,30.000000,1.000000,1.000000,1.000000,-1.000000
25%,607.475000,70.000000,2.000000,1.000000,1.000000,-1.000000
50%,752.000000,94.000000,2.000000,2.000000,2.000000,0.000000
75%,1069.250000,140.500000,3.000000,2.000000,2.000000,61.100000
max,2115.000000,385.000000,5.000000,5.000000,4.000000,164.500000